language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - main
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
