language: node_js
install:
  - npm install
node_js:
  - 12
cache:
  directories:
    - node_modules
branches:
  only:
    - main
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  github-token: $GH_TOKEN
  on:
    branch: main
  local-dir: public
